[package]
name = "caxe"
version = "0.3.1"
edition = "2024"
description = "A modern C/C++ project manager that cuts through build system complexity. Zero config, smart dependencies, and parallel builds."
authors = ["Dhimas Ardinata dhimasardinatapp@gmail.com"]
license = "MIT"
repository = "https://github.com/dhimasardinata/caxe"
readme = "README.md"
keywords = ["cpp", "build-tool", "package-manager", "c", "make"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[[bin]]
name = "cx"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
clap_complete = "4.5.38"
colored = "3.0.0"
console = "0.16.2"
dirs = "6.0.0"
git2 = { version = "0.20.3", features = ["vendored-openssl"] }
indicatif = "0.18.3"
inquire = "0.9.1"
notify = "8.2.0"
rayon = "1.11.0"
rhai = "1.23.6"
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.9"
ureq = { version = "3.1", features = ["json"] }
walkdir = "2.5.0"
regex = "1.10"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
